export const menuData = [
  {
    group: 'PRODUCT',
    items: [
      { label: 'Watch Demo', href: '/watch-demo' },
      { label: 'Pricing', href: '/pricing' },
      { label: 'Paid vs. Free', href: '/comparison' },
      { label: 'Accessibility', href: '/accessibility' },
      { label: 'Featured Releases', href: '/features' },
      { label: 'Changelog', href: '/changelog' },
      { label: 'Status', href: '/status' },
    ],
  },
  {
    group: 'WHY SLACK?',
    items: [
      { label: 'Slack vs. Email', href: '/slack-vs-email' },
      { label: 'Enterprise', href: '/enterprise' },
      { label: 'Small Business', href: '/small-business' },
      { label: 'Productivity', href: '/productivity' },
      { label: 'Task Management', href: '/task-management' },
      { label: 'Scale', href: '/scale' },
      { label: 'Trust', href: '/trust' },
    ],
  },
  {
    group: 'FEATURES',
    items: [
      { label: 'Channels', href: '/channels' },
      { label: 'Slack Connect', href: '/slack-connect' },
      { label: 'Workflow Builder', href: '/workflow-builder' },
      { label: 'Messaging', href: '/messaging' },
      { label: 'Huddles', href: '/huddles' },
      { label: 'Canvas', href: '/canvas' },
      { label: 'Lists', href: '/lists' },
      { label: 'Clips', href: '/clips' },
      { label: 'Apps & Integrations', href: '/apps-integrations' },
      { label: 'File Sharing', href: '/file-sharing' },
      { label: 'Slack AI', href: '/slack-ai' },
      { label: 'Agentforce', href: '/agentforce' },
      { label: 'Security', href: '/security' },
      {
        label: 'Enterprise Key Management',
        href: '/enterprise-key-management',
      },
      { label: 'Slack Atlas', href: '/slack-atlas' },
    ],
  },
  {
    group: 'SOLUTIONS',
    items: [
      { label: 'Engineering', href: '/engineering' },
      { label: 'IT', href: '/it' },
      { label: 'Customer Service', href: '/customer-service' },
      { label: 'Sales', href: '/sales' },
      { label: 'Project Management', href: '/project-management' },
      { label: 'Marketing', href: '/marketing' },
      { label: 'Security', href: '/solutions-security' },
      { label: 'Manufacture, Auto & Energy', href: '/manufacture-auto-energy' },
      { label: 'Technology', href: '/technology' },
      { label: 'Media', href: '/media' },
      { label: 'Financial Services', href: '/financial-services' },
      { label: 'Retail', href: '/retail' },
      { label: 'Public Sector', href: '/public-sector' },
      { label: 'Education', href: '/education' },
      { label: 'Health & Life Sciences', href: '/health-life-sciences' },
    ],
  },
  {
    group: 'RESOURCES',
    items: [
      { label: 'Help Center', href: '/help-center' },
      { label: "What's New", href: '/whats-new' },
      { label: 'Resources Library', href: '/resources-library' },
      { label: 'Slack Blog', href: '/slack-blog' },
      { label: 'Community', href: '/community' },
      { label: 'Customer Stories', href: '/customer-stories' },
      { label: 'Events', href: '/events' },
      { label: 'Developers', href: '/developers' },
      { label: 'Partners', href: '/partners' },
      { label: 'Partner Offers', href: '/partner-offers' },
      { label: 'Slack Marketplace', href: '/slack-marketplace' },
      { label: 'Slack Certified', href: '/slack-certified' },
    ],
  },
  {
    group: 'COMPANY',
    items: [
      { label: 'About Us', href: '/about' },
      { label: 'News', href: '/news' },
      { label: 'Media Kit', href: '/media-kit' },
      { label: 'Brand Center', href: '/brand-center' },
      { label: 'Careers', href: '/careers' },
      { label: 'Swag Store', href: '/swag-store' },
      { label: 'Engineering Blog', href: '/engineering-blog' },
      { label: 'Design Blog', href: '/design-blog' },
      { label: 'Contact Us', href: '/contact' },
    ],
  },
];

export const brandsLogo = [
  'ameritrade-logo.png',
  'target-logo.png',
  'uber.png',
  'logo-onemedical.png',
  'time-logo.png',
  'intuit.png',
  'oracle-logo.png',
];
