export const timezones = [
  { label: '(UTC−12:00) Baker Island', value: 'UTC-12:00' },
  { label: '(UTC−11:00) American Samoa', value: 'UTC-11:00' },
  { label: '(UTC−10:00) Hawaii', value: 'UTC-10:00' },
  { label: '(UTC−09:00) Alaska', value: 'UTC-09:00' },
  { label: '(UTC−08:00) Pacific Time (US & Canada)', value: 'UTC-08:00' },
  { label: '(UTC−07:00) Mountain Time (US & Canada)', value: 'UTC-07:00' },
  { label: '(UTC−06:00) Central Time (US & Canada)', value: 'UTC-06:00' },
  { label: '(UTC−05:00) Eastern Time (US & Canada)', value: 'UTC-05:00' },
  { label: '(UTC−04:00) Atlantic Time (Canada)', value: 'UTC-04:00' },
  { label: '(UTC−03:00) Buenos Aires', value: 'UTC-03:00' },
  { label: '(UTC−02:00) South Georgia', value: 'UTC-02:00' },
  { label: '(UTC−01:00) Azores', value: 'UTC-01:00' },
  { label: '(UTC±00:00) Greenwich Mean Time', value: 'UTC+00:00' },
  { label: '(UTC+01:00) Central European Time', value: 'UTC+01:00' },
  { label: '(UTC+02:00) Eastern European Time', value: 'UTC+02:00' },
  { label: '(UTC+03:00) Moscow, St. Petersburg', value: 'UTC+03:00' },
  { label: '(UTC+03:30) Tehran', value: 'UTC+03:30' },
  { label: '(UTC+04:00) UAE Standard Time', value: 'UTC+04:00' },
  { label: '(UTC+05:00) Pakistan Standard Time', value: 'UTC+05:00' },
  { label: '(UTC+05:30) India Standard Time', value: 'UTC+05:30' },
  { label: '(UTC+06:00) Bangladesh Standard Time', value: 'UTC+06:00' },
  { label: '(UTC+07:00) Bangkok, Hanoi, Jakarta', value: 'UTC+07:00' },
  { label: '(UTC+08:00) China Standard Time', value: 'UTC+08:00' },
  { label: '(UTC+09:00) Japan Standard Time', value: 'UTC+09:00' },
  { label: '(UTC+09:30) Australian Central Time', value: 'UTC+09:30' },
  { label: '(UTC+10:00) Australian Eastern Time', value: 'UTC+10:00' },
  { label: '(UTC+11:00) Solomon Islands', value: 'UTC+11:00' },
  { label: '(UTC+12:00) New Zealand Standard Time', value: 'UTC+12:00' },
  { label: '(UTC+13:00) Samoa', value: 'UTC+13:00' },
  { label: '(UTC+14:00) Line Islands', value: 'UTC+14:00' },
];
export const languages = [
  { label: 'Deutsch (Deutschland)', value: 'de-de' },
  { label: 'English (UK)', value: 'en-uk' },
  { label: 'English (US)', value: 'en-us' },
  { label: 'Español (España)', value: 'es-es' },
  { label: 'Español (Latinoamérica)', value: 'es-la' },
  { label: 'Français (France)', value: 'fr-fr' },
  { label: 'Italiano (Italia)', value: 'it-it' },
  { label: 'Português (Brasil)', value: 'pt-br' },
  { label: '日本語', value: 'ja-jp' },
  { label: '简体中文', value: 'zh-cn' },
  { label: '繁體中文', value: 'zh-tw' },
  { label: '한국어', value: 'ko-kr' },
];
